name: IaC Workflow (Terraform)
run-name: terraform ${{ github.event.inputs.action }}
on:
    workflow_dispatch:
        inputs:
            action:
                type: choice
                description: Terraform action to perform
                options:
                    - apply
                    - destroy
                    - plan
            env:
                type: choice
                description: Target environment
                options:
                    - dev
                    - prod

jobs:
    terraform-action:
        environment: ${{ github.event.inputs.env }}
        runs-on: ubuntu-latest
        steps:
            - name: Clone Github Repo
              uses: actions/checkout@v4

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: eu-west-1

            - name: Infra initiate
              working-directory: ./infra
              run: terraform init

            - name: Terraform plan
              if: ${{ github.event.inputs.action == 'plan' }}
              working-directory: ./infra
              run: terraform plan

            - name: Terraform apply
              if: ${{ github.event.inputs.action == 'apply' }}
              working-directory: ./infra
              run: terraform apply -auto-approve

            - name: Terraform destroy
              if: ${{ github.event.inputs.action == 'destroy' }}
              working-directory: ./infra
              run: terraform destroy -auto-approve
